server:
  port: 8080
  apiOnly: False
BHxl:
  location: assets/phavu.G19833.gnm1.div.Moghaddam_Mamidi_2016.712_geno_MDP_ADP_BASE_imputed_sub10k.vcf.gz
  name: Bean CAP diversity panels, assembly 1
  format: vcf