server:
  port: 8080
  apiOnly: False

G8RH:
  location: assets/cicar.CDCFrontier.div.vonWettberg_Chang_2018_sub10k.vcf.gz
  name: cicar.CDCFrontier.div.vonWettberg_Chang_2018_sub10k.vcf.gz
  format: vcf
